/** Nomes de colunas das tabelas Gold consumidas pelo front-end. */
export const GOLD_COLUMNS = {
  SALDO: 'saldo',
  ADMISSOES: 'admissoes',
  DESLIGAMENTOS: 'desligamentos',
  COMPETENCIA: 'competencia',
  UF: 'uf',
  MUNICIPIO: 'municipio',
  SECAO: 'secao',
  CBO_OCUPACAO: 'cbo2002ocupacao',
  SEXO: 'sexo',
  FAIXA_ETARIA: 'faixa_etaria',
  GRAUDEINSTRUCAO: 'graudeinstrucao',
  PAIS: 'pais',
  CONTINENTE: 'continente',
  RACACOR: 'racacor',
  SALARIO_MEDIO: 'salario_medio',
  SALARIO_MEDIANO: 'salario_mediano',
  SALARIO_P25: 'salario_p25',
  SALARIO_P75: 'salario_p75',
  SALARIO_MIN: 'salario_min',
  SALARIO_MAX: 'salario_max',
  N_SALARIOS_VALIDOS: 'n_salarios_validos',
  ICTT: 'ICTT',
  RANKING_ICTT: 'ranking_ictt',
  PERCENTIL_ICTT: 'percentil_ictt',
  CLASSE_ICTT: 'classe_ictt',
  TOOLTIP_RESUMO: 'tooltip_resumo',
  STATUS_CALCULO: 'status_calculo',
  MUNICIPIO_NORM: 'municipio_norm',
  COMPETENCIA_STR: 'competencia_str',
  DIM_DINAMISMO: 'dim_dinamismo',
  DIM_REMUNERACAO: 'dim_remuneracao',
  DIM_QUALIDADE_EMPREGO: 'dim_qualidade_emprego',
  DIM_PERFIL_TRABALHADOR: 'dim_perfil_trabalhador',
  DIM_COMPLEXIDADE: 'dim_complexidade',
  SHANNON_CBO: 'shannon_cbo',
} as const

export type GoldColumnName = (typeof GOLD_COLUMNS)[keyof typeof GOLD_COLUMNS]
